// Code generated by MockGen. DO NOT EDIT.
// Source: ./adal.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	adal "github.com/Azure/go-autorest/autorest/adal"
	gomock "github.com/golang/mock/gomock"
)

// MockAdalService is a mock of AdalService interface.
type MockAdalService struct {
	ctrl     *gomock.Controller
	recorder *MockAdalServiceMockRecorder
}

// MockAdalServiceMockRecorder is the mock recorder for MockAdalService.
type MockAdalServiceMockRecorder struct {
	mock *MockAdalService
}

// NewMockAdalService creates a new mock instance.
func NewMockAdalService(ctrl *gomock.Controller) *MockAdalService {
	mock := &MockAdalService{ctrl: ctrl}
	mock.recorder = &MockAdalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdalService) EXPECT() *MockAdalServiceMockRecorder {
	return m.recorder
}

// NewOAuthConfig mocks base method.
func (m *MockAdalService) NewOAuthConfig(activeDirectoryEndpoint, tenantID string) (*adal.OAuthConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOAuthConfig", activeDirectoryEndpoint, tenantID)
	ret0, _ := ret[0].(*adal.OAuthConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewOAuthConfig indicates an expected call of NewOAuthConfig.
func (mr *MockAdalServiceMockRecorder) NewOAuthConfig(activeDirectoryEndpoint, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOAuthConfig", reflect.TypeOf((*MockAdalService)(nil).NewOAuthConfig), activeDirectoryEndpoint, tenantID)
}

// NewServicePrincipalToken mocks base method.
func (m *MockAdalService) NewServicePrincipalToken(oauthConfig adal.OAuthConfig, clientID, secret, resource string, callbacks ...adal.TokenRefreshCallback) (*adal.ServicePrincipalToken, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{oauthConfig, clientID, secret, resource}
	for _, a := range callbacks {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewServicePrincipalToken", varargs...)
	ret0, _ := ret[0].(*adal.ServicePrincipalToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewServicePrincipalToken indicates an expected call of NewServicePrincipalToken.
func (mr *MockAdalServiceMockRecorder) NewServicePrincipalToken(oauthConfig, clientID, secret, resource interface{}, callbacks ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{oauthConfig, clientID, secret, resource}, callbacks...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewServicePrincipalToken", reflect.TypeOf((*MockAdalService)(nil).NewServicePrincipalToken), varargs...)
}
