---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: nginx
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
        - s3:CreateBucket
        - s3:DeleteBucket
        - s3:PutBucketTagging
        - s3:GetBucketTagging
        - s3:PutBucketPublicAccessBlock
        - s3:GetBucketPublicAccessBlock
        - s3:PutEncryptionConfiguration
        - s3:GetEncryptionConfiguration
        - s3:PutLifecycleConfiguration
        - s3:GetLifecycleConfiguration
        - s3:GetBucketLocation
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
        - s3:ListBucketMultipartUploads
        - s3:AbortMultipartUpload
        - s3:ListMultipartUploadParts
      effect: Allow
      resource: '*'
  secretRef:
    name: nginx-credentials
    namespace: default
  serviceAccountNames:
  - nginx
