apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cloud-credential-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-credential-operator-role
subjects:
- kind: ServiceAccount
  name: cloud-credential-operator
  namespace: openshift-cloud-credential-operator
