kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-credential-operator
  namespace: openshift-config-managed
  annotations:
    capability.openshift.io/name: CloudCredential
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
subjects:
- kind: ServiceAccount
  name: cloud-credential-operator
  namespace: openshift-cloud-credential-operator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cloud-credential-operator-role
