apiVersion: operator.openshift.io/v1
kind: CloudCredential
metadata:
  name: cluster
  annotations:
    capability.openshift.io/name: CloudCredential
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
spec:
  credentialsMode: ""
