apiVersion: operator.openshift.io/v1
kind: CloudCredential
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
spec:
  credentialsMode: ""
