kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-credential-operator
  namespace: openshift-cloud-credential-operator
subjects:
- kind: ServiceAccount
  name: cloud-credential-operator
  namespace: openshift-cloud-credential-operator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cloud-credential-operator-role
