apiVersion: v1
kind: Service
metadata:
  name: cco-metrics
  namespace: openshift-cloud-credential-operator
spec:
  ports:
  - name: cco-metrics
    port: 2112
    protocol: TCP
    targetPort: 2112
  selector:
    app: cloud-credential-operator
  sessionAffinity: None
  type: ClusterIP
