apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: cloud-credential-operator-serving-cert
  name: cco-metrics
  namespace: openshift-cloud-credential-operator
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    app: cloud-credential-operator
  sessionAffinity: None
  type: ClusterIP
