apiVersion: cloudcredential.openshift.io/v1beta1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-ingress
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: cloud-credentials
    namespace: openshift-ingress
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1beta1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - s3:CreateBucket
      - s3:DeleteBucket
      - elasticloadbalancing:AddTags
      - elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
      - elasticloadbalancing:ConfigureHealthCheck
      - elasticloadbalancing:CreateLoadBalancer
      - elasticloadbalancing:CreateLoadBalancerListeners
      - elasticloadbalancing:DeleteLoadBalancer
      - elasticloadbalancing:DeleteLoadBalancerListeners
      - elasticloadbalancing:DescribeLoadBalancerAttributes
      - elasticloadbalancing:DescribeLoadBalancers
      - elasticloadbalancing:DescribeTags
      - elasticloadbalancing:ModifyLoadBalancerAttributes
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      resource: "*"
---
