// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCredentialsProviderSpec) DeepCopyInto(out *AWSCredentialsProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.StatementEntries != nil {
		in, out := &in.StatementEntries, &out.StatementEntries
		*out = make([]StatementEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCredentialsProviderSpec.
func (in *AWSCredentialsProviderSpec) DeepCopy() *AWSCredentialsProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AWSCredentialsProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSCredentialsProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCredentialsProviderStatus) DeepCopyInto(out *AWSCredentialsProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCredentialsProviderStatus.
func (in *AWSCredentialsProviderStatus) DeepCopy() *AWSCredentialsProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AWSCredentialsProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSCredentialsProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureCredentialsProviderSpec) DeepCopyInto(out *AzureCredentialsProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]RoleBinding, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureCredentialsProviderSpec.
func (in *AzureCredentialsProviderSpec) DeepCopy() *AzureCredentialsProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AzureCredentialsProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureCredentialsProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureCredentialsProviderStatus) DeepCopyInto(out *AzureCredentialsProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureCredentialsProviderStatus.
func (in *AzureCredentialsProviderStatus) DeepCopy() *AzureCredentialsProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AzureCredentialsProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureCredentialsProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsRequest) DeepCopyInto(out *CredentialsRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsRequest.
func (in *CredentialsRequest) DeepCopy() *CredentialsRequest {
	if in == nil {
		return nil
	}
	out := new(CredentialsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialsRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsRequestCondition) DeepCopyInto(out *CredentialsRequestCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsRequestCondition.
func (in *CredentialsRequestCondition) DeepCopy() *CredentialsRequestCondition {
	if in == nil {
		return nil
	}
	out := new(CredentialsRequestCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsRequestList) DeepCopyInto(out *CredentialsRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CredentialsRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsRequestList.
func (in *CredentialsRequestList) DeepCopy() *CredentialsRequestList {
	if in == nil {
		return nil
	}
	out := new(CredentialsRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialsRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsRequestSpec) DeepCopyInto(out *CredentialsRequestSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.ProviderSpec != nil {
		in, out := &in.ProviderSpec, &out.ProviderSpec
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsRequestSpec.
func (in *CredentialsRequestSpec) DeepCopy() *CredentialsRequestSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialsRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsRequestStatus) DeepCopyInto(out *CredentialsRequestStatus) {
	*out = *in
	if in.LastSyncTimestamp != nil {
		in, out := &in.LastSyncTimestamp, &out.LastSyncTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ProviderStatus != nil {
		in, out := &in.ProviderStatus, &out.ProviderStatus
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CredentialsRequestCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsRequestStatus.
func (in *CredentialsRequestStatus) DeepCopy() *CredentialsRequestStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialsRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPCredentialsProviderSpec) DeepCopyInto(out *GCPCredentialsProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.PredefinedRoles != nil {
		in, out := &in.PredefinedRoles, &out.PredefinedRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPCredentialsProviderSpec.
func (in *GCPCredentialsProviderSpec) DeepCopy() *GCPCredentialsProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GCPCredentialsProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPCredentialsProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPCredentialsProviderStatus) DeepCopyInto(out *GCPCredentialsProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPCredentialsProviderStatus.
func (in *GCPCredentialsProviderStatus) DeepCopy() *GCPCredentialsProviderStatus {
	if in == nil {
		return nil
	}
	out := new(GCPCredentialsProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPCredentialsProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IAMPolicyCondition) DeepCopyInto(out *IAMPolicyCondition) {
	{
		in := &in
		*out = make(IAMPolicyCondition, len(*in))
		for key, val := range *in {
			var outVal map[string]runtime.RawExtension
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(IAMPolicyConditionKeyValue, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMPolicyCondition.
func (in IAMPolicyCondition) DeepCopy() IAMPolicyCondition {
	if in == nil {
		return nil
	}
	out := new(IAMPolicyCondition)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IAMPolicyConditionKeyValue) DeepCopyInto(out *IAMPolicyConditionKeyValue) {
	{
		in := &in
		*out = make(IAMPolicyConditionKeyValue, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMPolicyConditionKeyValue.
func (in IAMPolicyConditionKeyValue) DeepCopy() IAMPolicyConditionKeyValue {
	if in == nil {
		return nil
	}
	out := new(IAMPolicyConditionKeyValue)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCredentialsProviderSpec) DeepCopyInto(out *OpenStackCredentialsProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCredentialsProviderSpec.
func (in *OpenStackCredentialsProviderSpec) DeepCopy() *OpenStackCredentialsProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackCredentialsProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackCredentialsProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackCredentialsProviderStatus) DeepCopyInto(out *OpenStackCredentialsProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackCredentialsProviderStatus.
func (in *OpenStackCredentialsProviderStatus) DeepCopy() *OpenStackCredentialsProviderStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackCredentialsProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackCredentialsProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtCredentialsProviderSpec) DeepCopyInto(out *OvirtCredentialsProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtCredentialsProviderSpec.
func (in *OvirtCredentialsProviderSpec) DeepCopy() *OvirtCredentialsProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtCredentialsProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtCredentialsProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtCredentialsProviderStatus) DeepCopyInto(out *OvirtCredentialsProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtCredentialsProviderStatus.
func (in *OvirtCredentialsProviderStatus) DeepCopy() *OvirtCredentialsProviderStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtCredentialsProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtCredentialsProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleBinding) DeepCopyInto(out *RoleBinding) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleBinding.
func (in *RoleBinding) DeepCopy() *RoleBinding {
	if in == nil {
		return nil
	}
	out := new(RoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatementEntry) DeepCopyInto(out *StatementEntry) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyCondition != nil {
		in, out := &in.PolicyCondition, &out.PolicyCondition
		*out = make(IAMPolicyCondition, len(*in))
		for key, val := range *in {
			var outVal map[string]runtime.RawExtension
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(IAMPolicyConditionKeyValue, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatementEntry.
func (in *StatementEntry) DeepCopy() *StatementEntry {
	if in == nil {
		return nil
	}
	out := new(StatementEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereCredentialsProviderSpec) DeepCopyInto(out *VSphereCredentialsProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]VSpherePermission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereCredentialsProviderSpec.
func (in *VSphereCredentialsProviderSpec) DeepCopy() *VSphereCredentialsProviderSpec {
	if in == nil {
		return nil
	}
	out := new(VSphereCredentialsProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSphereCredentialsProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSphereCredentialsProviderStatus) DeepCopyInto(out *VSphereCredentialsProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSphereCredentialsProviderStatus.
func (in *VSphereCredentialsProviderStatus) DeepCopy() *VSphereCredentialsProviderStatus {
	if in == nil {
		return nil
	}
	out := new(VSphereCredentialsProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSphereCredentialsProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSpherePermission) DeepCopyInto(out *VSpherePermission) {
	*out = *in
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSpherePermission.
func (in *VSpherePermission) DeepCopy() *VSpherePermission {
	if in == nil {
		return nil
	}
	out := new(VSpherePermission)
	in.DeepCopyInto(out)
	return out
}
