apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-identity-webhook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: pod-identity-webhook.mutate.io
    admissionReviewVersions:
      - v1beta1
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: pod-identity-webhook
        namespace: openshift-cloud-credential-operator
        path: "/mutate"
    namespaceSelector:
      matchExpressions:
        - key: openshift.io/run-level
          operator: NotIn
          values:
            - "0"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
