apiVersion: v1
kind: Service
metadata:
  name: pod-identity-webhook
  namespace: openshift-cloud-credential-operator
  annotations:
    prometheus.io/port: "443"
    prometheus.io/scheme: "https"
    prometheus.io/scrape: "true"
    service.beta.openshift.io/serving-cert-secret-name: pod-identity-webhook
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: pod-identity-webhook
